routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PublicController@index')->name('homepage');

//  API
Route::get('api/log', 'ApiController@api_log')->name('api_log');
Route::post('card', 'ApiController@rfid_card')->name('card');
Route::get('user-info/{id}', 'ApiController@user_info')->name('info');
Route::get('logs', 'ApiController@logs')->name('logs');
Route::post('save-member/{id}', 'ApiController@save_member')->name('save_member');

Auth::routes([
	// 'register' => false
]);

// admin routes
Route::get('daily-logs', 'HomeController@daily_logs')->name('daily_logs');
Route::get('dashboard', 'HomeController@index')->name('home');
Route::get('print', 'HomeController@print_report')->name('print');

// settings
Route::get('settings', 'SettingsController@index')->name('settings');
Route::post('settings/profile', 'SettingsController@profile_update')->name('profile.update');
Route::post('settings/password', 'SettingsController@password_update')->name('password.update');

// Restful Controllers
Route::resources([
	'users' => 'UsersController',
	'roles' => 'RolesController',
	'members' => 'MembersController',
	'devices' => 'DevicesController',
]);

resources/views/admin.blade.php
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta name="description" content="Neon Admin Panel" />
	<meta name="author" content="" />
	<meta name="csrf-token" content="{{ csrf_token() }}">
    <title>RFID READER</title>

	<link rel="icon" href="{{asset('assets/images/favicon.ico')}}">

	<link rel="stylesheet" href="{{asset('assets/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/font-icons/entypo/css/entypo.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/font-icons/font-awesome/css/font-awesome.min.css')}}">
	<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic">
	<link rel="stylesheet" href="{{asset('assets/css/bootstrap.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/neon-core.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/neon-theme.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/neon-forms.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/neon-rtl.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/custom.css')}}">

	<script src="{{asset('assets/js/jquery-1.11.3.min.js')}}"></script>

	<!--[if lt IE 9]><script src="assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
	
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	@yield('styles')
	<style>
	th{text-align:left;}
	</style>

</head>
<body class="page-body" data-url="{{ url('/') }}">

	<div class="page-container"><!-- add class "sidebar-collapsed" to close sidebar by default, "chat-visible" to make chat appear always -->
		
		<div class="sidebar-menu">

			<div class="sidebar-menu-inner">
				
				<header class="logo-env">

					<!-- logo -->
					{{-- <div class="logo">
						<a href="#">
							<img src="{{asset('assets/images/logo@2x.png')}}" width="120" alt="" />
						</a>
					</div> --}}

					<!-- logo collapse icon -->
					<div class="sidebar-collapse">
						<a href="#" class="sidebar-collapse-icon"><!-- add class "with-animation" if you want sidebar to have animation during expanding/collapsing transition -->
							<i class="entypo-menu"></i>
						</a>
					</div>

									
					<!-- open/close menu icon (do not remove if you want to enable menu on mobile devices) -->
					<div class="sidebar-mobile-menu visible-xs">
						<a href="#" class="with-animation"><!-- add class "with-animation" to support animation -->
							<i class="entypo-menu"></i>
						</a>
					</div>

				</header>
				
										
				<ul id="main-menu" class="main-menu">
					<!-- add class "multiple-expanded" to allow multiple submenus to open -->
					<!-- class "auto-inherit-active-class" will automatically add "active" class for parent elements who are marked already with class "active" -->
					@if ( Auth::user()->hasRole('admin') )
					<li>
		                <a href="{{ route('home') }}"> 
		                    <i class="fa fa-th-large"></i> <span class="nav-label">Daily Logs</span>
		                </a>
		            </li>

		            <li>
		                <a href="{{ route('members.index') }}"> 
		                    <i class="fa fa-users"></i> <span class="nav-label">Members</span>
		                </a>
		            </li>

		            <li>
		                <a href="{{ route('devices.index') }}"> 
		                    <i class="fa fa-mobile-phone"></i> <span class="nav-label">Devices</span>
		                </a>
		            </li>
		    
		            <li>
		                <a href="{{ route('users.index') }}"> 
		                    <i class="fa fa-user"></i> <span class="nav-label">Users</span>
		                </a>
		            </li>
		            {{-- <li>
		                <a href="{{ route('roles.index') }}"> 
		                    <i class="fa fa-lock"></i> <span class="nav-label">User Roles</span>
		                </a>
		            </li> --}}
		            @endif

		            @if ( Auth::user()->hasRole('member') )
		            <li>
		                <a href="{{ route('home', ['id' => Auth::user()->member()]) }}">
		                    <i class="fa fa-th-large"></i> <span class="nav-label">Logs</span>
		                </a>
		            </li>
		            <li>
		                <a href="{{ route('members.edit', Auth::user()->member()) }}">
		                    <i class="fa fa-user"></i> <span class="nav-label">User Details</span>
		                </a>
		            </li>
		            @endif

		            <li>
		                <a href="{{ route('settings') }}">
		                    <i class="fa fa-cogs"></i> <span class="nav-label">Profile Settings</span>
		                </a>
		            </li>

				</ul>
				
			</div>

		</div>

		<div class="main-content">
			<div class="row">
		
				<!-- Profile Info and Notifications -->
				<div class="col-md-6 col-sm-8 clearfix">
			
					<ul class="user-info pull-left pull-none-xsm">
			
						<!-- Profile Info -->
						<li class="profile-info dropdown"><!-- add class "pull-right" if you want to place this from right -->
			
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<img src="{{asset('img/profile_small.jpg')}}" alt="" class="img-circle" width="44">
								{{ Auth::user()->name }}
							</a>
			
							<ul class="dropdown-menu">
			
								<!-- Reverse Caret -->
								<li class="caret"></li>
			
								<!-- Profile sub-links -->
			
								<li>
									<a href="{{ route('settings') }}">
					                    <i class="fa fa-cogs"></i> 
					                	Profile Settings
					                </a>
								</li>
			
								<li>
									<a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
										<i class="entypo-logout right"></i>
										Log Out 
									</a>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			
				<!-- Raw Links -->
				<div class="col-md-6 col-sm-4 clearfix hidden-xs">
					<ul class="list-inline links-list pull-right">
						<li class="sep"></li>
						<li>
							<a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
		                        Log Out <i class="entypo-logout right"></i>
		                    </a>

		                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
		                        {{ csrf_field() }}
		                    </form>
						</li>
					</ul>
				</div>
			
			</div>
			
			<hr>
			
			
			@yield('action')
			

			
			<h2>{{ ( $title ) ? $title:'' }}</h2>
            <span>{{ ( $description ) ? $description:'' }}</span>
            
            <div class="row">
				@include('inc.alert')
			</div>
			<br>

			
			@yield('content')
			
            <div class="clearfix"></div>
            

			<footer class="main">&copy; {{ date('Y') }} <strong></strong> Admin Panel</footer>
		</div><!-- .main-content -->
	</div><!-- .page-container -->

	<!-- Bottom scripts (common) -->
	<script src="{{asset('assets/js/gsap/TweenMax.min.js')}}"></script>
	<script src="{{asset('assets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js')}}"></script>
	<script src="{{asset('assets/js/bootstrap.js')}}"></script>
	<script src="{{asset('assets/js/joinable.js')}}"></script>
	<script src="{{asset('assets/js/resizeable.js')}}"></script>
	<script src="{{asset('assets/js/neon-api.js')}}"></script>

	<!-- JavaScripts initializations and stuff -->
	<script src="{{asset('assets/js/neon-custom.js')}}"></script>
	<!-- Demo Settings -->
	<script src="{{asset('assets/js/neon-demo.js')}}"></script>
	@yield('scripts')

</body>
</html>

resources/views/daily_logs.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>RFID READER</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{{asset('bootstrap/css/bootstrap.min.css')}}">

        <style>
        .wrap {
            background: url(../../img/bg-dark.jpg) no-repeat center center;
            background-size: cover;
            min-height: 900px;
        }
        tbody{
            width: 100%;
        }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">RFID Scanner</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    @if (Route::has('login'))
                        @if (Auth::check())
                            @if ( Auth::user()->hasRole('admin') )
                                <li class="nav-item active">
                                    <a class="nav-link" href="{{ route('home') }}">Dashboard</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('members.index') }}">Members</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('users.index') }}">Users</a>
                                </li>
                            @endif
                            @if ( Auth::user()->hasRole('member') )
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('members.edit', Auth::user()->member()) }}">Account Details</a>
                            </li>
                            @endif
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('settings') }}">Settings</a>
                            </li>
                        @else
                            <li class="nav-item active">
                                <a class="nav-link" href="{{ route('login') }}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">Register</a>
                            </li>
                        @endif
                    @endif
                </ul>
            </div>
        </nav>
        
        <div class="wrap">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-3">
                    <div align="center">
                        <img src="{{ asset('img/logo.png') }}" alt="" class="img-fluid mt-5">
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-9">
                    
                    <div class="card bg-light border-light mt-5 mb-5">
                        <div class="card-header">Scan Details</div>
                        <div class="card-body text-dark">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="photo" align="center">
                                        <img width="100%" src="{{ asset('img/placeholder.jpg') }}" alt="" class="img-fluid img-thumbnail">
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <table class="table table-inverse">
                                        <tbody>
                                            <tr>
                                                <td><b>Status:</b></td>
                                                <td>
                                                    <span class="badge badge-info mt-1">STATUS</span>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td><b>Date & Time:</b></td>
                                                <td class="time"></td>
                                            </tr>
                                            <tr>
                                                <td><b>First Name:</b></td>
                                                <td class="fname"></td>
                                            </tr>
                                            <tr>
                                                <td><b>Last Name:</b></td>
                                                <td class="lname"></td>
                                            </tr>
                                            <tr>
                                                <td><b>Middle Name:</b></td>
                                                <td class="mname"></td>
                                            </tr>
                                            {{-- <tr>
                                                <td><b>Address:</b></td>
                                                <td class="addr"></td>
                                            </tr>
                                            <tr>
                                                <td><b>Phone:</b></td>
                                                <td class="phone"></td>
                                            </tr> --}}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
        
        <script src="{{ asset('js/app.js') }}"></script>
        <script>
        jQuery(document).ready(function($) {
            setInterval(function(){
                jQuery.ajax({
                    url: '{{ route('logs') }}',
                    type: 'get',
                    data: {},
                    success: function (data) {
                        $('.fname').text(data.first_name);
                        $('.lname').text(data.last_name);
                        $('.mname').text(data.middle_name);
                        // $('.addr').text(data.address);
                        // $('.phone').text(data.phone);
                        if (data.photo != '') {
                            $('.photo img').attr('src',data.photo);
                        } else {
                            $('.photo img').attr('src','img/placeholder.jpg');
                        }
                        var btn = $('.table .badge');
                        switch(data.log_type){
                            case '':
                                btn.attr('class','badge badge-info mt-1');
                                btn.html('STATUS');
                                $('.table .time').html('');
                            break;
                            case 'logout':
                                btn.attr('class','badge badge-danger mt-1');
                                btn.html('LOGGED OUT');
                                $('.table .time').html(data.time);
                            break;
                            case 'login':
                                btn.attr('class','badge badge-success mt-1');
                                btn.html('LOGGED IN');
                                $('.table .time').html(data.time);
                            break;
                        }
                    }
                });
            },1000);
        });
        </script>
    </body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection